import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer/Footer';
import React from 'react';
import Navbar from '../components/NavBar/Navbar';
import Banner from '../components/Banner/Banner';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UofTHacks X</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/uofthacks.ico' />
      </Head>
      <Navbar/>
      <Banner/>
      <div className={styles.footer}>
        <Footer></Footer>
      </div>
      
    </div>
  );
}
