import Head from 'next/head';
import { styled } from '../stitches.config';
import Footer from '../components/Footer/Footer';
import React from 'react';
import Navbar from '../components/NavBar/Navbar';
import Banner from '../components/Banner/Banner';
import Background from '../components/Background/Background';

const HomeWrapper = styled('div', {
  padding: '0 2rem',
  minHeight: '100vh',
});

const FooterWrapper = styled('div', {
  display: 'flex',
  flex: '1',
  padding: '2rem 0',
  borderTop: '1px solid #eaeaea',
  justifyContent: 'center',
  alignItems: 'center',
  '&a': {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexGrow: '1'
  }
});

export default function Home() {
  return (
    <HomeWrapper>
      <Head>
        <title>UofTHacks X</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/uofthacks.ico' />
      </Head>
      <Navbar/>
      <Background/>
      <Banner/>
      <FooterWrapper>
        <Footer/>
      </FooterWrapper>
    </HomeWrapper>
  );
}
